import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ANDROID = ROOT / "android_app/app/src/main/java/com/brz/gauge/trips"


class CalendarBookkeepingAndMultiPhoneTests(unittest.TestCase):
    def test_driving_calendar_and_total_overview_are_present(self):
        main = (ANDROID / "MainActivity.kt").read_text(encoding="utf-8")
        calendar = (ANDROID / "DrivingCalendarView.kt").read_text(encoding="utf-8")
        self.assertIn('card(body, "驾驶总览")', main)
        self.assertIn('card(body, "驾驶日历")', main)
        self.assertIn("DrivingCalendarView(this)", main)
        self.assertIn("data class DrivingDayActivity", calendar)
        self.assertIn("repeat(weeks)", calendar)
        self.assertIn("setOnDaySelected", calendar)
        self.assertIn("today.with(TemporalAdjusters.nextOrSame(DayOfWeek.SUNDAY))", calendar)
        self.assertIn("date.isAfter(visibleEnd)", calendar)
        self.assertIn("fun colorForDistance(distanceM: Long)", calendar)
        self.assertIn("distanceM < 100_000L", calendar)
        self.assertNotIn("maxDistance", calendar)
        self.assertIn('label("0km"', main)
        self.assertIn('label("100km+"', main)
        self.assertNotIn("色阶：低于 25", main)
        self.assertIn("DrivingCalendarView.ACTIVITY_COLORS", main)
        self.assertIn('bookkeepingMetric("累计里程"', main)
        self.assertIn('bookkeepingMetric("总平均油耗"', main)
        self.assertIn("totalFuel.toDouble() / it * 100.0", main)
        self.assertIn("private val showTripAccelerationDetails = false", main)
        self.assertIn("if (showTripAccelerationDetails)", main)
        self.assertIn('return "${dateFormat.format(value)}\\n${timeFormat.format(value)}"', main)
        self.assertIn("refreshRevisionToggle", main)
        self.assertIn('label("历史驾驶记录"', main)
        self.assertIn("list.addHeaderView(body, null, false)", main)
        self.assertIn("historyEmptyText.visibility = if (trips.isEmpty())", main)

    def test_bookkeeping_has_swipe_sections_and_visual_statistics(self):
        main = (ANDROID / "MainActivity.kt").read_text(encoding="utf-8")
        database = (ANDROID / "ExpenseDatabase.kt").read_text(encoding="utf-8")
        chart = (ANDROID / "BookkeepingChartView.kt").read_text(encoding="utf-8")
        maintenance = (ANDROID / "MaintenanceSchedule.kt").read_text(encoding="utf-8")
        daily_chart = (ANDROID / "DailyExpenseBreakdownView.kt").read_text(encoding="utf-8")
        self.assertIn('listOf("加油", "保养", "日常", "统计")', main)
        self.assertIn("attachAccountingSwipe()", main)
        self.assertIn("override fun onFling", main)
        self.assertIn('card(body, "保养项目跟踪")', main)
        self.assertIn("calculateMaintenanceDueStates", main)
        self.assertIn("MaintenanceDueStatus.OVERDUE", main)
        self.assertIn("MaintenanceDueStatus.MISSING_ODOMETER", main)
        self.assertNotIn("state.maintenanceSevereConditions", main)
        self.assertIn("setMultiChoiceItems", main)
        self.assertIn("selectedMaintenanceKinds", main)
        self.assertIn("按填写里程推荐项目", main)
        self.assertIn("recommendedMaintenanceKinds", main)
        self.assertIn("再手动增删项目", main)
        self.assertIn('distinct().joinToString("、")', main)
        self.assertIn("bookkeepingMonthDivider", main)
        self.assertIn("monthGroup.sumOf { it.amount }", main)
        self.assertIn("monthGroup.sumOf { it.cost }", main)
        self.assertIn("state.odometerDisplayEnabled", main)
        self.assertIn("MaintenanceServiceKind.entries.map", main)
        self.assertNotIn("MaintenanceServiceGroup", maintenance)
        self.assertNotIn("_INSPECTION", maintenance)
        self.assertIn("fun recommendedMaintenanceKinds", maintenance)
        self.assertIn("isNearServiceMilestone", maintenance)
        self.assertIn("ENGINE_OIL", maintenance)
        self.assertIn("ENGINE_OIL_FILTER", maintenance)
        self.assertIn('"发动机油", "更换", 5_000, 6', maintenance)
        self.assertIn("FUEL_ADDITIVE", maintenance)
        self.assertIn("FUEL_FILTER", maintenance)
        self.assertIn("MANUAL_TRANSMISSION_OIL", maintenance)
        self.assertIn("REAR_DIFFERENTIAL_OIL", maintenance)
        self.assertIn("SPARK_PLUGS", maintenance)
        self.assertIn('"火花塞", "更换", 60_000, null', maintenance)
        self.assertIn("ENGINE_COOLANT", maintenance)
        self.assertIn("firstIntervalKm = 220_000", maintenance)
        self.assertIn("100_000, 60", maintenance)
        self.assertNotIn("severeIntervalKm", maintenance)
        self.assertIn("dueKm - currentOdometerKm", maintenance)
        self.assertIn("km <= 0.0 -> MaintenanceDueStatus.OVERDUE", maintenance)
        self.assertIn("从 0 km 起算", main)
        self.assertIn("首次阈值", main)
        self.assertIn("MonthlyExpenseSummary", main)
        self.assertIn("BookkeepingChartView(this)", main)
        self.assertIn('card(body, "$year 年小类花费")', main)
        self.assertIn("DailyExpenseBreakdownView(this)", main)
        self.assertIn("DailyExpenseKind.entries.forEachIndexed", main)
        self.assertIn("canvas.drawArc", daily_chart)
        self.assertIn("本年度日常花费分类图", daily_chart)
        self.assertIn("primaryBookkeepingAction", main)
        self.assertIn("bookkeepingMetric", main)
        self.assertIn("bookkeepingEmpty", main)
        self.assertIn("content.animate().alpha(1f)", main)
        self.assertIn('field(if (category == ExpenseCategory.DAILY) "详细（可选）"', main)
        self.assertIn("DailyExpenseKind.entries.map { it.title }", main)
        self.assertIn('REPAIR("维修", R.drawable.ic_expense_repair)', (ANDROID / "ExpenseRecord.kt").read_text(encoding="utf-8"))
        self.assertIn('VIOLATION("违章", R.drawable.ic_expense_violation)', (ANDROID / "ExpenseRecord.kt").read_text(encoding="utf-8"))
        self.assertTrue((ROOT / "android_app/app/src/main/res/drawable/ic_expense_repair.xml").exists())
        self.assertTrue((ROOT / "android_app/app/src/main/res/drawable/ic_expense_violation.xml").exists())
        self.assertIn('label("${date.monthValue}月"', main)
        self.assertIn("setImageResource(iconRes)", main)
        self.assertIn("CREATE TABLE expenses", database)
        self.assertIn("item.maintenance", chart)
        self.assertIn("item.daily", chart)
        self.assertIn("repeat(4)", chart)
        self.assertIn("暂无月度开销", chart)
        self.assertNotIn("if (item.total > 0.0 && index == values.lastIndex)", chart)
        self.assertIn("items.forEach", chart)
        self.assertIn('canvas.drawText("${item.month.monthValue}月"', chart)
        self.assertIn('card(body, "全部月度明细")', main)
        self.assertIn("allMonthlyExpenseSummaries()", main)
        self.assertIn("recordedMonths.minOrNull()", main)
        self.assertIn("ChronoUnit.MONTHS.between(first, last)", main)
        self.assertIn("allMonths.asReversed().forEachIndexed", main)
        self.assertIn('fmt("合计  ¥%.2f", month.total)', main)
        self.assertIn('Triple("加油", month.fuel', main)
        self.assertIn('Triple("保养", month.maintenance', main)
        self.assertIn('Triple("日常", month.daily', main)
        adapter = (ANDROID / "TripAdapter.kt").read_text(encoding="utf-8")
        row = (ROOT / "android_app/app/src/main/res/layout/trip_row.xml").read_text(encoding="utf-8")
        self.assertIn("tripMonthDivider", adapter)
        self.assertIn("private fun tripMonth", adapter)
        self.assertIn("@+id/tripMonthDivider", row)

    def test_release_contains_no_owner_bookkeeping_seed_data(self):
        expense_database = (ANDROID / "ExpenseDatabase.kt").read_text(encoding="utf-8")
        main = (ANDROID / "MainActivity.kt").read_text(encoding="utf-8")
        self.assertFalse((ANDROID / "CuratedBookkeeping2026.kt").exists())
        self.assertNotIn("importOwnerExpensesOnce", main)
        self.assertNotIn("importCurated2026", expense_database)
        self.assertNotIn("owner_expenses_2026", main)
        self.assertIn('SQLiteOpenHelper(context, "brz_expenses.db", null, 2)', expense_database)
        self.assertIn('arrayOf("配件用品", ExpenseCategory.DAILY.code, "车辆配件")', expense_database)
        self.assertNotIn("DROP TABLE", expense_database)
        self.assertNotIn("DELETE FROM expenses", expense_database)
        expense_record = (ANDROID / "ExpenseRecord.kt").read_text(encoding="utf-8")
        for category in ("停车", "通行", "车辆洗护", "维修", "配件用品", "保险", "证件手续", "违章", "其他"):
            self.assertIn(f'("{category}", R.drawable.ic_expense_', expense_record)

    def test_protocol_three_keeps_history_for_independent_phone_cursors(self):
        storage = (ROOT / "main/bsp_obd_dsp/nvs_storage.c").read_text(encoding="utf-8")
        database = (ANDROID / "TripDatabase.kt").read_text(encoding="utf-8")
        service = (ANDROID / "TripSyncService.kt").read_text(encoding="utf-8")
        protocol = (ANDROID / "TripBleProtocol.kt").read_text(encoding="utf-8")

        self.assertIn("TRIP_SYNC_PROTOCOL_VERSION 3", storage)
        ack = storage.split("esp_err_t nvs_trip_sync_ack", 1)[1].split("/* Helpers */", 1)[0]
        self.assertNotIn("memmove", ack)
        self.assertIn("Do not delete acknowledged records", ack)
        self.assertIn("fun latestKnownId(deviceId: String)", database)
        self.assertIn("database.latestKnownId(address)", service)
        self.assertIn("if (m.version >= 3)", service)
        self.assertIn("it.version in 2..3", protocol)

    def test_manual_trip_split_preserves_totals_and_sync_tombstone(self):
        main = (ANDROID / "MainActivity.kt").read_text(encoding="utf-8")
        database = (ANDROID / "TripDatabase.kt").read_text(encoding="utf-8")
        record = (ANDROID / "TripRecord.kt").read_text(encoding="utf-8")
        adapter = (ANDROID / "TripAdapter.kt").read_text(encoding="utf-8")
        mileage = (ANDROID / "MileageEstimator.kt").read_text(encoding="utf-8")
        range_estimator = (ANDROID / "RangeEstimator.kt").read_text(encoding="utf-8")

        self.assertIn('"手动拆分这条行程"', main)
        self.assertIn("private fun splitTripRecord", main)
        self.assertIn('val confirmButton = button("确定拆分")', main)
        self.assertIn('(resources.displayMetrics.heightPixels * 0.56f)', main)
        self.assertIn("trip.distanceM - distanceM", main)
        self.assertIn("trip.durationS - durationS", main)
        self.assertIn("trip.fuelMl - fuelMl", main)
        self.assertIn("maxSpeedKmh = null", main)
        self.assertIn("fun splitTrip(original: TripRecord", database)
        self.assertIn("first.durationS + second.durationS != original.durationS", database)
        self.assertIn("first.distanceM + second.distanceM != original.distanceM", database)
        self.assertIn("first.fuelMl + second.fuelMl != original.fuelMl", database)
        self.assertIn('"deleted_trips", null, marker', database)
        self.assertIn("trip_id > 0", database)
        self.assertIn("fun localSplitId", record)
        self.assertIn('"$it-${splitPartLabel}"', record)
        self.assertIn("val sequenceId: Long", record)
        self.assertIn('Triple("手动拆分"', adapter)
        self.assertIn("it.sequenceId > anchorTripId", mileage)
        self.assertIn(".map { it.sequenceId }", mileage)
        self.assertIn("compareByDescending<TripRecord> { it.sequenceId }", range_estimator)


if __name__ == "__main__":
    unittest.main()
