// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenPageLogo_screen_init(void)
{
    ui_ScreenPageLogo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPageLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenPageLogo, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_helpers_style_screen_bg(ui_ScreenPageLogo);
    lv_obj_set_style_bg_opa(ui_ScreenPageLogo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
#if USE_CUSTOM_BOOT_LOGO == 1
    LV_IMG_DECLARE(imgBootLogoCustom);
    // Customer-defined boot image (static picture, centered)
    imageLogo = lv_img_create(ui_ScreenPageLogo);
    lv_img_set_src(imageLogo, &imgBootLogoCustom);
    lv_obj_align(imageLogo, LV_ALIGN_CENTER, 0, 0);

    // White border ring (consistent with the other pages)
    lv_obj_t *spinnerLogo = ui_helpers_create_ring(ui_ScreenPageLogo, 10);   // white ring: static circular border
#elif USE_GIF_LOGO == 1
    imageLogo = lv_gif_create(ui_ScreenPageLogo);
    lv_gif_set_src(imageLogo, &gifSnake400);
    lv_obj_align(imageLogo, LV_ALIGN_CENTER, 0, 0);
#else
    // Subaru Tecnica International wordmark.
    imageLogo = lv_img_create(ui_ScreenPageLogo);
    lv_img_set_src(imageLogo, &pngLogoSTI);
    lv_obj_align(imageLogo, LV_ALIGN_CENTER, 0, -10);

    lv_obj_t *subtitle = lv_label_create(ui_ScreenPageLogo);
    lv_label_set_text(subtitle, "SUBARU TECNICA INTERNATIONAL");
    lv_obj_set_style_text_font(subtitle, &ui_font_FontTypoderSize16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(subtitle, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(subtitle, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_align(subtitle, LV_ALIGN_CENTER, 0, 70);

    // White border ring (same as Gear page style)
    lv_obj_t *spinnerLogo = ui_helpers_create_ring(ui_ScreenPageLogo, 10);
#endif
    lv_obj_add_event_cb(ui_ScreenPageLogo, ui_event_logo_background, LV_EVENT_ALL, NULL);
}
