// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: OBD_PRJ
// Modified: EasterEgg page replaced with Device Info page

#include "../ui.h"
#include "bsp_obd_dsp/nvs_storage.h"
#include "bsp_obd_dsp/elm327_ble_client.h"
#include "bsp_obd_dsp/espnow_link.h"

#ifndef OBD_GAUGE_BUILD_TAG
#define OBD_GAUGE_BUILD_TAG "local"
#endif

#ifndef OBD_GAUGE_FIRMWARE_VERSION
#define OBD_GAUGE_FIRMWARE_VERSION "3.2.9"
#endif

void ui_device_odometer_refresh(void)
{
    if (!ui_LabelEasterEggOdometer) return;

    nvs_odometer_snapshot_t data;
    nvs_odometer_get_snapshot(&data);
    if (!data.display_enabled) {
        lv_obj_add_flag(ui_LabelEasterEggOdometer, LV_OBJ_FLAG_HIDDEN);
        return;
    }

    /* Total odometer is the one deliberate exception to display rounding:
     * show only completed whole kilometres. */
    lv_label_set_text_fmt(ui_LabelEasterEggOdometer, "%lu km",
                          (unsigned long)(data.odometer_x10_km / 10U));
    lv_obj_clear_flag(ui_LabelEasterEggOdometer, LV_OBJ_FLAG_HIDDEN);
}

void ui_ScreenPageEasterEgg_screen_init(void)
{
    ui_ScreenPageEasterEgg = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPageEasterEgg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenPageEasterEgg, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_helpers_style_screen_bg(ui_ScreenPageEasterEgg);
    lv_obj_set_style_bg_opa(ui_ScreenPageEasterEgg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // White border ring
    lv_obj_t *spinner_ring = ui_helpers_create_ring(ui_ScreenPageEasterEgg, 10);

    /* ---- Device Info Page ----
       Kept minimal on purpose: role + OBD link state + firmware build tag.
       The expanded ring gives the wordmark and long build text the full panel. */
    lv_obj_t *sti_logo = lv_img_create(ui_ScreenPageEasterEgg);
    lv_img_set_src(sti_logo, &pngLogoSTI);
    /* Use the high-resolution master but keep this denser page's visual
       footprint near the old size so it cannot cover the status block. */
    lv_img_set_zoom(sti_logo, 192); /* 75%: 340x142 -> about 255x107 */
    lv_obj_align(sti_logo, LV_ALIGN_TOP_MID, 0, 40);

    // Role + connection state: master/standalone show BLE (ELM327), slave shows its master
    uint8_t device_role = nvs_cfg_get()->device_role;
    bool is_slave = (device_role == ESPNOW_ROLE_SLAVE);
    const char *mode_str = is_slave ? "SLAVE"
                         : (device_role == ESPNOW_ROLE_MASTER) ? "MASTER" : "STANDALONE";
    const char *conn_label, *conn_name, *conn_status;
    if (is_slave) {
        bool linked = espnow_link_slave_has_data();
        const char *mname = espnow_link_get_master_name();
        conn_label  = "SLAVE";
        conn_name   = (linked && mname[0]) ? mname : "--";
        conn_status = linked ? "Linked" : "Waiting";
    } else {
        const char *ble_name = elm327_ble_get_connected_name();
        if (!ble_name || ble_name[0] == '\0') ble_name = "Not set";
        conn_label  = "BLE";
        conn_name   = ble_name;
        conn_status = elm327_ble_is_connected() ? "Connected" : "Disconnected";
    }

    ui_LabelEasterEggInfo = lv_label_create(ui_ScreenPageEasterEgg);
    lv_label_set_long_mode(ui_LabelEasterEggInfo, LV_LABEL_LONG_WRAP);
    lv_obj_set_width(ui_LabelEasterEggInfo, 360);
    lv_label_set_text_fmt(ui_LabelEasterEggInfo,
        "MODE: %s\n"
        "%s: %s\n"
        "Status: %s\n"
        "FW: %s\n"
        "BUILD: %s",
        mode_str, conn_label, conn_name, conn_status,
        OBD_GAUGE_FIRMWARE_VERSION, OBD_GAUGE_BUILD_TAG);
    lv_obj_set_style_text_font(ui_LabelEasterEggInfo, &ui_font_FontTypoderSize16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelEasterEggInfo, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelEasterEggInfo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelEasterEggInfo, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_align(ui_LabelEasterEggInfo, LV_ALIGN_CENTER, 0, 0);

    // Phone-synchronized odometer: keep the existing fixed position.
    ui_LabelEasterEggOdometer = lv_label_create(ui_ScreenPageEasterEgg);
    lv_label_set_text(ui_LabelEasterEggOdometer, "");
    lv_obj_set_width(ui_LabelEasterEggOdometer, 320);
    lv_obj_set_style_text_align(ui_LabelEasterEggOdometer, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_LabelEasterEggOdometer, &ui_font_FontTypoderSize20, LV_PART_MAIN);
    lv_obj_set_style_text_color(ui_LabelEasterEggOdometer, lv_color_hex(0xD8E0E8), LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_LabelEasterEggOdometer, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_align(ui_LabelEasterEggOdometer, LV_ALIGN_BOTTOM_MID, 0, -102);
    lv_obj_add_flag(ui_LabelEasterEggOdometer, LV_OBJ_FLAG_HIDDEN);
    ui_device_odometer_refresh();

    /* OTA is intentionally not exposed on the gauge UI.  The phone's explicit
     * parked confirmation remains the only supported way to enter OTA mode. */
    lv_obj_move_foreground(ui_LabelEasterEggOdometer);

    imageEasterEgg = NULL;

    // Gesture event on screen for page navigation
    lv_obj_add_event_cb(ui_ScreenPageEasterEgg, ui_event_easter_egg_background, LV_EVENT_ALL, NULL);
}
