// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: OBD_PRJ

#include "../ui.h"
#include "../ui_ext.h"
#include "app_obd_dsp/vehicle_profiles.h"

#include <math.h>

#define GEAR_RPM_MARKER_COUNT 5
#define GEAR_RPM_CENTER        233
#define GEAR_RPM_MARKER_INNER  148
#define GEAR_RPM_MARKER_OUTER  172
#define GEAR_RPM_LABEL_RADIUS  132

static lv_obj_t * s_lower_gear_markers[GEAR_RPM_MARKER_COUNT];
static lv_obj_t * s_lower_gear_labels[GEAR_RPM_MARKER_COUNT];
static lv_point_t s_lower_gear_marker_points[GEAR_RPM_MARKER_COUNT][2];

static void ui_gear_hide_lower_markers(void)
{
    for (uint8_t i = 0; i < GEAR_RPM_MARKER_COUNT; ++i) {
        if (s_lower_gear_markers[i]) lv_obj_add_flag(s_lower_gear_markers[i], LV_OBJ_FLAG_HIDDEN);
        if (s_lower_gear_labels[i]) lv_obj_add_flag(s_lower_gear_labels[i], LV_OBJ_FLAG_HIDDEN);
    }
}

void ui_gear_page_update_visuals(uint16_t rpm, uint16_t warning_rpm, uint16_t speed_kmh,
                                 uint8_t current_gear, uint16_t yellowline_rpm)
{
    if (!ui_GearPageArcGearNumBack) return;

    uint32_t dial_rpm = rpm > RPM_DIAL_MAX ? RPM_DIAL_MAX : rpm;
    lv_arc_set_value(ui_GearPageArcGearNumBack, dial_rpm * 100U / RPM_DIAL_MAX);

    lv_color_t rpm_color = warning_rpm >= RPM_REDLINE ? lv_color_hex(0xFF2020) :
                           warning_rpm >= yellowline_rpm ? lv_color_hex(0xFFD21F) :
                                                   ui_theme_color_lv(UI_COLOR_ARC_INDICATOR);
    lv_obj_set_style_arc_color(ui_GearPageArcGearNumBack, rpm_color,
                               LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_GearPageRpmText, rpm_color,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gear_hide_lower_markers();
    const vehicle_profile_t * profile = vehicle_profile_get_active();
    if (!profile || speed_kmh == 0 || current_gear < 2 ||
        current_gear > profile->gear_count || profile->final_drive_ratio <= 0.0f ||
        profile->tire_rolling_radius_m <= 0.0f) {
        return;
    }

    const float wheel_rpm = ((float)speed_kmh / 3.6f) * 60.0f /
                            (2.0f * 3.14159265f * profile->tire_rolling_radius_m);
    uint8_t slot = 0;
    for (int gear = (int)current_gear - 1; gear >= 1 && slot < GEAR_RPM_MARKER_COUNT; --gear) {
        const float predicted = wheel_rpm * profile->final_drive_ratio * profile->gear_ratios[gear];
        if (predicted <= 0.0f || predicted > (float)RPM_REDLINE) continue;

        const int predicted_rpm = (int)(predicted + 0.5f);
        const float angle_deg = 90.0f + predicted * 360.0f / (float)RPM_DIAL_MAX;
        const float angle_rad = angle_deg * 3.14159265f / 180.0f;
        const int inner_x = GEAR_RPM_CENTER + (int)(cosf(angle_rad) * GEAR_RPM_MARKER_INNER);
        const int inner_y = GEAR_RPM_CENTER + (int)(sinf(angle_rad) * GEAR_RPM_MARKER_INNER);
        const int outer_x = GEAR_RPM_CENTER + (int)(cosf(angle_rad) * GEAR_RPM_MARKER_OUTER);
        const int outer_y = GEAR_RPM_CENTER + (int)(sinf(angle_rad) * GEAR_RPM_MARKER_OUTER);
        const int marker_x = inner_x < outer_x ? inner_x : outer_x;
        const int marker_y = inner_y < outer_y ? inner_y : outer_y;
        const int label_x = GEAR_RPM_CENTER + (int)(cosf(angle_rad) * GEAR_RPM_LABEL_RADIUS) - 11;
        const int label_y = GEAR_RPM_CENTER + (int)(sinf(angle_rad) * GEAR_RPM_LABEL_RADIUS) - 10;
        lv_color_t marker_color = predicted_rpm >= yellowline_rpm ? lv_color_hex(0xFFD21F) :
                                                                      ui_theme_color_lv(UI_COLOR_TEXT_PRIMARY);

        s_lower_gear_marker_points[slot][0].x = (lv_coord_t)(inner_x - marker_x);
        s_lower_gear_marker_points[slot][0].y = (lv_coord_t)(inner_y - marker_y);
        s_lower_gear_marker_points[slot][1].x = (lv_coord_t)(outer_x - marker_x);
        s_lower_gear_marker_points[slot][1].y = (lv_coord_t)(outer_y - marker_y);
        lv_obj_set_pos(s_lower_gear_markers[slot], marker_x, marker_y);
        lv_line_set_points(s_lower_gear_markers[slot], s_lower_gear_marker_points[slot], 2);
        lv_obj_set_style_line_color(s_lower_gear_markers[slot], marker_color, 0);
        lv_obj_clear_flag(s_lower_gear_markers[slot], LV_OBJ_FLAG_HIDDEN);

        lv_obj_set_pos(s_lower_gear_labels[slot], label_x, label_y);
        lv_label_set_text_fmt(s_lower_gear_labels[slot], "%d", gear);
        lv_obj_set_style_text_color(s_lower_gear_labels[slot], marker_color, 0);
        lv_obj_clear_flag(s_lower_gear_labels[slot], LV_OBJ_FLAG_HIDDEN);
        ++slot;
    }
}

void ui_ScreenPageGear_screen_init(void)
{
    ui_ScreenPageGear = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPageGear, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenPageGear, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_helpers_style_screen_bg(ui_ScreenPageGear);
    lv_obj_set_style_bg_opa(ui_ScreenPageGear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Bezel ring (color from the active theme)
    ui_SpinnerGearPage = ui_helpers_create_ring(ui_ScreenPageGear, 10);

    lv_obj_set_style_arc_color(ui_SpinnerGearPage, ui_theme_color_lv(UI_COLOR_RING), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpinnerGearPage, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SpinnerGearPage, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_GearPageRpmText = lv_label_create(ui_ScreenPageGear);
    lv_obj_set_width(ui_GearPageRpmText, 320);
    lv_obj_set_height(ui_GearPageRpmText, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_GearPageRpmText, LV_ALIGN_CENTER);
    lv_obj_set_y(ui_GearPageRpmText, -58);
    lv_label_set_long_mode(ui_GearPageRpmText, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_GearPageRpmText, "0");
    lv_obj_set_style_text_align(ui_GearPageRpmText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_GearPageRpmText, ui_theme_color_lv(UI_COLOR_TEXT_PRIMARY), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GearPageRpmText, &ui_font_FontTypoderSize56, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GearPageRpmUnit = lv_label_create(ui_ScreenPageGear);
    lv_obj_set_align(ui_GearPageRpmUnit, LV_ALIGN_CENTER);
    lv_obj_set_y(ui_GearPageRpmUnit, -15);
    lv_label_set_text(ui_GearPageRpmUnit, "RPM");
    lv_obj_set_style_text_color(ui_GearPageRpmUnit, ui_theme_color_lv(UI_COLOR_TEXT_SECONDARY), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GearPageRpmUnit, &ui_font_FontTypoderSize16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GearPageArcLabelGearNumText = lv_label_create(ui_ScreenPageGear);
    lv_obj_set_width(ui_GearPageArcLabelGearNumText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GearPageArcLabelGearNumText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GearPageArcLabelGearNumText, LV_ALIGN_CENTER);
    lv_obj_set_y(ui_GearPageArcLabelGearNumText, 55);
    lv_label_set_text(ui_GearPageArcLabelGearNumText, "N");
    lv_obj_set_style_text_color(ui_GearPageArcLabelGearNumText, ui_theme_color_lv(UI_COLOR_TEXT_PRIMARY), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GearPageArcLabelGearNumText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GearPageArcLabelGearNumText, &ui_font_FontTypoderSize44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GearPageGearUnit = lv_label_create(ui_ScreenPageGear);
    lv_obj_set_align(ui_GearPageGearUnit, LV_ALIGN_CENTER);
    lv_obj_set_y(ui_GearPageGearUnit, 94);
    lv_label_set_text(ui_GearPageGearUnit, "GEAR");
    lv_obj_set_style_text_color(ui_GearPageGearUnit, ui_theme_color_lv(UI_COLOR_TEXT_SECONDARY), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GearPageGearUnit, &ui_font_FontTypoderSize16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GearPageArcGearNumBack = lv_arc_create(ui_ScreenPageGear);
    lv_obj_set_width(ui_GearPageArcGearNumBack,340);
    lv_obj_set_height(ui_GearPageArcGearNumBack,340);
    lv_obj_set_align(ui_GearPageArcGearNumBack, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GearPageArcGearNumBack, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_GearPageArcGearNumBack, 0);
    lv_arc_set_rotation(ui_GearPageArcGearNumBack, 90);
    lv_arc_set_bg_angles(ui_GearPageArcGearNumBack, 0, 360);
    lv_obj_set_style_arc_color(ui_GearPageArcGearNumBack, ui_theme_color_lv(UI_COLOR_ARC_TRACK), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_GearPageArcGearNumBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_GearPageArcGearNumBack, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_GearPageArcGearNumBack, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_GearPageArcGearNumBack, ui_theme_color_lv(UI_COLOR_ARC_INDICATOR), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_GearPageArcGearNumBack, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_GearPageArcGearNumBack, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_GearPageArcGearNumBack, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_GearPageArcGearNumBack, ui_theme_color_lv(UI_COLOR_ARC_INDICATOR), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GearPageArcGearNumBack, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    // Predicted RPM markers for lower gears. Each short radial tick sits on the
    // RPM track; the small number identifies which lower gear it represents.
    for (uint8_t i = 0; i < GEAR_RPM_MARKER_COUNT; ++i) {
        s_lower_gear_marker_points[i][0] = (lv_point_t){0, 0};
        s_lower_gear_marker_points[i][1] = (lv_point_t){0, 0};
        s_lower_gear_markers[i] = lv_line_create(ui_ScreenPageGear);
        lv_line_set_points(s_lower_gear_markers[i], s_lower_gear_marker_points[i], 2);
        lv_obj_clear_flag(s_lower_gear_markers[i], LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_CLICKABLE);
        lv_obj_set_style_line_width(s_lower_gear_markers[i], 6, 0);
        lv_obj_set_style_line_rounded(s_lower_gear_markers[i], true, 0);
        lv_obj_add_flag(s_lower_gear_markers[i], LV_OBJ_FLAG_HIDDEN);

        s_lower_gear_labels[i] = lv_label_create(ui_ScreenPageGear);
        lv_obj_set_size(s_lower_gear_labels[i], 22, 20);
        lv_label_set_text(s_lower_gear_labels[i], "");
        lv_obj_set_style_text_align(s_lower_gear_labels[i], LV_TEXT_ALIGN_CENTER, 0);
        lv_obj_set_style_text_font(s_lower_gear_labels[i], &ui_font_FontTypoderSize16, 0);
        lv_obj_add_flag(s_lower_gear_labels[i], LV_OBJ_FLAG_HIDDEN);
    }

    ui_ImageGearBlackEar = lv_img_create(ui_ScreenPageGear);
    lv_img_set_src(ui_ImageGearBlackEar, &ui_img_pngblackear_png);
    lv_obj_set_width(ui_ImageGearBlackEar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageGearBlackEar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageGearBlackEar, 0);
    lv_obj_set_y(ui_ImageGearBlackEar, -142);
    lv_obj_set_align(ui_ImageGearBlackEar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageGearBlackEar, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageGearBlackEar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_GearPageArcGearNumBack, ui_event_gear_background, LV_EVENT_ALL, NULL);
    lv_obj_move_foreground(ui_SpinnerGearPage);   // bring the ring to the front
    lv_obj_add_event_cb(ui_ScreenPageGear, ui_event_gear_background, LV_EVENT_GESTURE, NULL);

}
