#!/usr/bin/env python3
"""Convert the STI wordmark into a compact black-backed LVGL RGB565 asset."""

from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "tools" / "sti_logo_source.png"
OUTPUT = ROOT / "main" / "export_path" / "images" / "pngLogoSTI.c"
VAR_NAME = "pngLogoSTI"
# The AMOLED is 466 px wide. Keep enough source pixels for crisp diagonals
# while leaving the outer gauge ring and subtitle clear.
TARGET_WIDTH = 340


def rgb565_bytes(image: Image.Image) -> bytearray:
    raw = bytearray()
    for r, g, b in image.getdata():
        value = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        # The firmware is built with LV_COLOR_16_SWAP=1, therefore true-color
        # image assets must store RGB565 in display order (high byte first).
        # The old low/high order turned the red STI mark yellow on hardware.
        raw.extend((value >> 8, value & 0xFF))
    return raw


def main() -> None:
    source = Image.open(SOURCE).convert("RGB")
    # The downloaded wordmark is red on white. Crop to the non-white mark and
    # key the white background to black so it blends into the AMOLED UI.
    mask = Image.new("1", source.size)
    mask.putdata([0 if min(pixel) > 235 else 1 for pixel in source.getdata()])
    bbox = mask.getbbox()
    if bbox is None:
        raise RuntimeError("STI mark could not be detected")
    mark = source.crop(bbox)
    target_height = round(TARGET_WIDTH * mark.height / mark.width)
    mark = mark.resize((TARGET_WIDTH, target_height), Image.Resampling.LANCZOS)
    pixels = []
    for r, g, b in mark.getdata():
        whiteness = min(r, g, b)
        alpha = max(0.0, min(1.0, (235.0 - whiteness) / 90.0))
        pixels.append((round(r * alpha), round(g * alpha), round(b * alpha)))
    mark.putdata(pixels)
    raw = rgb565_bytes(mark)

    lines = [
        "// Auto-generated by tools/convert_sti_logo.py",
        f"// Source: {SOURCE.name}; cropped and resized to {mark.width}x{mark.height}",
        "// LV_COLOR_16_SWAP=1: RGB565 byte order is high, low",
        '#include "lvgl.h"',
        "",
        f"const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t {VAR_NAME}_map[] = {{",
    ]
    for offset in range(0, len(raw), 32):
        lines.append("  " + ", ".join(f"0x{byte:02x}" for byte in raw[offset:offset + 32]) + ",")
    lines.extend([
        "};",
        "",
        f"const lv_img_dsc_t {VAR_NAME} = {{",
        "  .header.cf = LV_IMG_CF_TRUE_COLOR,",
        "  .header.always_zero = 0,",
        "  .header.reserved = 0,",
        f"  .header.w = {mark.width},",
        f"  .header.h = {mark.height},",
        f"  .data_size = {len(raw)},",
        f"  .data = {VAR_NAME}_map,",
        "};",
        "",
    ])
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {OUTPUT} ({mark.width}x{mark.height}, {len(raw)} bytes)")


if __name__ == "__main__":
    main()
